// BOOKS

export const CREATE_BOOK_REQUEST="CREATE_BOOK_REQUEST"
export const CREATE_BOOK_SUCCESS="CREATE_BOOK_SUCCESS"
export const CREATE_BOOK_FAIL="CREATE_BOOK_FAIL"

// FETCH BOOKS

export const FETCH_BOOK_REQUEST="FETCH_BOOK_REQUEST"
export const FETCH_BOOK_SUCCESS="FETCH_BOOK_SUCCESS"
export const FETCH_BOOK_FAIL="FETCH_BOOK_FAIL"

// FETCH USERS
export const FETCH_USER_REQUEST="FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS="FETCH_USER_SUCCESS"
export const FETCH_USER_FAIL="FETCH_USER_FAIL"


// REGISTER USER
export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL="USER_REGISTER_FAIL"

// USER LOGIN

export const USER_LOGIN_REQUEST= "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS= "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL= "USER_LOGIN_FAIL"

// USER LOGOUT

export const USER_LOGOUT_SUCCESS='USER_LOGOUT_SUCCESS'